Reporting
jmix-framework/jmix-v1-v2-docs pull request #197
Opened 2021-06-07 03:07 UTC by BryanYin

All parts are done, ready for 1.0.0

2021-06-08 15:15 UTC, knstvk requested changes
Finished the review.
Thanks for your great work!

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/quick-start.adoc
> +[source, xml]
Add `indent=0` to all examples, e.g: `[source,xml,indent=0]`

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/quick-start.adoc
> +include::example$/ex1/src/main/resources/com/company/jmixreports/screen/bookpublication/book-publication-browse.xml[tags=list-print-action]
Try to minimize irrelevant information in the examples, otherwise there is too much visual noise. 
Use comments with ellipsis in the code and multiple tags, for example `include::.../User.java[tags=field-based-attr-1;field-based-attr-2]` 
Here would be better to see only this:
```
<actions>
    <!-- ... -->
    <action id="list" type="listPrintForm" caption="msg://printDetails"/> 
</actions>
<buttonsPanel id="buttonsPanel"
              alwaysVisible="true">
    <!-- ... -->
    <button id="list" action="bookPublicationsTable.list"/> 
</buttonsPanel>
```

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/quick-start.adoc
> +To add a query condition, you can directly add it in the *Query* field or by clicking the *Create* button. For example, we added a condition *where e.createdDate >=:createDt* in the *Query* field, th
Use monospace for code: `where e.createdDate >=:createDt`

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/data-structure.adoc
> +When creating or editing a report, *Report structure* tab will show as default:
"... *Report structure* tab is shown by default"

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/data-structure.adoc
> +[WARNING]
CAUTION is more appropriate here. See recommendations at https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions/

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/data-structure.adoc
> +def book = dataManager.load(Book.class).id(bookId).fetchPlan("book.edit").one()
In Groovy, you can refer to the class without `.class`, e.g.: `dataManager.load(Book).id(bookId)...`

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/data-structure.adoc
> +def accountService = applicationContext.getBean(AccountService.class);
`def accountService = applicationContext.getBean(AccountService)`

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/data-structure.adoc
> +You can use static methods of the `AppBeans` class to access any Spring beans of the middleware tier, for example:
Probably you forgot to remove this tip. The mentioning of `ApplicationContext` above is enough.

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/data-structure.adoc
> +The report template must contain fields with entity attribute names. Attribute names can use names in the existing fetch plan by check *Use existing fetch plan* or can be selected by the *Select enti
"... by checking ..."

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/data-structure.adoc
> +== Dataset types
"Dataset Types"

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/data-structure.adoc
> +[WARNING]
CAUTION is more appropriate here. See recommendations at https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions/

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/templates.adoc
> +== Template types
"Template Types"

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/templates.adoc
> +Each xref:creation/data-structure.adoc#report_bands[report band] must have a corresponding region in the template, which is named the same as the band. For instance, a report has two bands – Header a
Use LibreOffice everywhere

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/templates.adoc
> +[WARNING]
CAUTION here and below. Let's reserve WARNING for really dangerous situations.

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/templates.adoc
> +== Executing a report on an external server
"Executing External Reports"

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/templates.adoc
> +[[exec_report_on_external_server]]
exec_external_report

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/templates.adoc
> +The platform provides the ability to run a report on an external server by URL, such as Microsoft Reporting Services. To enable this feature, follow these steps:
"The Reports add-on allows you to run a report of an external service, such as Microsoft Reporting Services, and download its output. To define an external report, follow these steps:"

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/templates.adoc
> +* In the *Custom definition* field, specify the URL for the report in MS Reporting Services. Report parameters can be passed to the URL as `${param Alias}`.
"... specify the URL of the external report."

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/templates.adoc
> +== Output format compliance matrix
"Output Format Compliance Matrix"

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/configuration.adoc
> +The Reports add-on uses the cURL tool to create reports by URL. The property value represents the path to the cURL tool.
"The Reports add-on uses the cURL tool to run external reports."

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/parameter-and-format.adoc
> += Report parameters and field formatters
Please always use Title Case in section titles

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/parameter-and-format.adoc
> +Input parameters properties::
Make it a third-level subsection:
=== Input Parameters Properties

The same for subsections below.

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/parameter-and-format.adoc
> +To work with the `FileDescriptor`, use the `${imageFileId:WxH}` value formatter that accepts both the `FileDescriptor` `id` and the link to the `FileDecriptor` instance itself.
There is no more FileDescriptor in the framework (only in CUBA compatibility module). Could you find out how it works now? Consult with developers if needed.

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/parameter-and-format.adoc
> +* `invalid` – groovy closure which effectively fails validation if called from inside the script.
Perhaps it doesn't make sense for formatting script

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/permissions.adoc
> +The *Screens* list allows to specify, in which screens the report will be available when invoking xref:run-report.adoc#run_report_action[RunReportAction], xref:run-report.adoc#list_print_form_action[
"... allows you to specify ..."
typo: "applicaiton" → "application"

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/creation/localization.adoc
> +You can localize the report name, then in the report list, it will show the name in the language user selected. In order to do this, you need to go to the *Localization* tab and enter pairs, `++local
"You can localize the report name, then the report list will show the name in the language selected by the user on login."

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/run-report.adoc
> +[source, xml]
Make the same adjustments as per my comments in Quick Start section

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/run-report.adoc
> +== Report Execution History
Move it to a separate document as it was in the CUBA docs. It's a long section and it's not directly related to the topics on "how" to run reports.

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/run-report.adoc
> +. Save execution history for each report. The system administrator can use the report execution history to find out how often a report is executed, how many seconds of processing time is spent on a r
"... how much processing time is spent on a report, ..."

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/run-report.adoc
> +Output documents::
Make it subsections to include to right-side menu

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/run-report.adoc
> +The mechanism provides an ability to save output documents – report results files – in the {manual_platform}/file_storage.html[file storage]. This feature consumes a file storage disk space; it is co
Invalid link. Make a link to the Managing Files section.

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/run-report.adoc
> +Reports with output types xref:templates.adoc#template_chart[chart], xref:templates.adoc#pivotTable_output[pivot table], and xref:templates.adoc#table_output[table] do not have result files, so the e
Invalid links

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/api.adoc
> +== Getting the list of existing reports
Title Case

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/configuration.adoc
> +== Installing and Configuring OpenOffice
Let's keep only LibreOffice everywhere. It's proven to be much faster in conversion than OpenOffice.

2021-06-08 15:15 UTC, knstvk commented on content/modules/reports/pages/quick-start.adoc
> +As an example, we will create a simple application `Library` with several simple entities.
What about uploading the project on GitHub? We have an organization for sample projects: https://github.com/jmix-projects

2021-06-10 08:09 UTC, BryanYin commented on content/modules/reports/pages/creation/parameter-and-format.adoc
> +To work with the `FileDescriptor`, use the `${imageFileId:WxH}` value formatter that accepts both the `FileDescriptor` `id` and the link to the `FileDecriptor` instance itself.
Changed to: To work with the `FileRef`, use the `${imageFileId:WxH}` value formatter that accepts a `FileRef` instance or a URI of a file as a string.

2021-06-16 11:34 UTC, knstvk approved these changes
Please fix according to my last comments and then merge.

2021-06-16 11:34 UTC, knstvk commented on content/modules/reports/pages/creation/templates.adoc
> +image::exec_external_report.png[align="center"]
This image doesn't exist

2021-06-16 11:34 UTC, knstvk commented on content/modules/reports/pages/creation/permissions.adoc
> +The *Screens* list allows to specify, in which screens the report will be available when invoking xref:run-report.adoc#run_report_action[RunReportAction], xref:run-report.adoc#list_print_form_action[
Still "allows to specify". Must be "allows you to specify"

2021-06-16 11:34 UTC, knstvk commented on content/modules/reports/pages/api.adoc
> +/reports/api/report
The endpoints have been recently changed to /rest/reports/...

2021-06-16 15:03 UTC, merged