Update Backoffice UI section #348
jmix-framework/jmix-v1-v2-docs pull request #349
Opened 2022-03-09 12:28 UTC by oshiryaeva

Also updated Studio section: screenshots and Tool Window description

2022-03-09 12:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Haulmont/jmix-docs?pullRequest=349) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Haulmont/jmix-docs?pullRequest=349) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Haulmont/jmix-docs?pullRequest=349) it.</sub>

2022-03-09 14:22 UTC, knstvk requested changes
We also need redirects (see https://docs.antora.org/antora/latest/page/page-aliases/#page-aliases-attribute).

For example, in `content/modules/ui/pages/index.adoc`:
```
= User Interface
:page-aliases: backoffice-ui:index.adoc
```

In `content/modules/ui/pages/vcl/components.adoc`:
```
= Components
:page-aliases: backoffice-ui:vcl/components.adoc
```

2022-03-09 14:22 UTC, knstvk commented on content/modules/ROOT/nav.adoc
> -include::backoffice-ui:partial$nav.adoc[]
The module name should be just `ui`. So here will be `include::ui:partial$nav.adoc[]`.

2022-03-10 13:48 UTC, oshiryaeva commented
Requested changes are pushed to the branch

2022-03-13 14:16 UTC, merged