testing approaches 1 5
jmix-framework/jmix-v1-v2-docs pull request #560
Opened 2023-06-20 07:35 UTC by mariodavid

- initial version of docs for testing
- small improvements on unit tests
- add first part of integration tests
- add first part of integration tests
- finish integration tests
- remove changes from 2.0 again

2023-06-20 08:20 UTC, knstvk requested changes
Need some cosmetic changes

2023-06-20 08:20 UTC, knstvk commented on content/modules/testing/pages/integration-tests.adoc
> +== Dependency Injection in Tests
Please add anchors to all headers

2023-06-20 08:20 UTC, knstvk commented on content/modules/testing/pages/integration-tests.adoc
> +== Overriding behaviour of the application
Title Case

2023-06-23 07:21 UTC, mariodavid commented on content/modules/testing/pages/integration-tests.adoc
> +== Dependency Injection in Tests
done

2023-06-23 07:21 UTC, mariodavid commented on content/modules/testing/pages/integration-tests.adoc
> +== Overriding behaviour of the application
done

2023-06-23 13:02 UTC, merged