Document Flowui Styling 627
jmix-framework/jmix-v1-v2-docs pull request #809
Opened 2024-07-12 13:07 UTC by glebfox

2024-07-16 09:22 UTC, knstvk requested changes
Some formatting and structuring comments.

2024-07-16 09:22 UTC, knstvk commented on content/modules/flow-ui/pages/themes/themes.adoc
> +The application theme is applied using the `@Theme` annotation with the name of the theme folder as a parameter. The `@Theme` must be placed on the class that implements the `AppShellConfigurator` in
"The `@Theme` must be.." - incorrect. Either "The `@Theme` annotation must be..." or "`@Theme` must be..."

2024-07-16 09:22 UTC, knstvk commented on content/modules/flow-ui/pages/themes/reusable-theme.adoc
> += Reusable theme
Title Case

Also, what about placing this section inside `themes.adoc` as a last subsection? It's short and in fact continues the explanation of themes structure.

2024-07-16 09:22 UTC, knstvk commented on content/modules/flow-ui/pages/themes/styling-ui-components.adoc
> +For example, if we want to apply a background color and a border to a `TextField`, we need to apply styles to the *shadow part* called `input-field`:
Prefer second person - "you".
https://youtrack.haulmont.com/articles/PLAT-A-40/Jmix-Documentation#Writing

2024-07-16 09:22 UTC, knstvk commented on content/modules/flow-ui/pages/themes/reusable-theme.adoc
> +image::themes/theme-addon-structure.png[align="center"]
Use `width` attribute to set image width to real value, e.g. `[align="center", width="662"]`
Please update for all images.

2024-07-16 09:22 UTC, knstvk commented on content/modules/flow-ui/pages/themes/pluggable-styles.adoc
> +An Add-on may contain a file with custom styles in the `src/main/resources/META-INF/resources/` directory. To add these styles to the resulting app the `jmix.ui.export-styles` property need to be add
No need in upper case: "An add-on ..."

Use "application" instead of "app", write simpler sentences:
"To add these styles to the resulting application, define the `jmix.ui.export-styles` property in the `module.properties` file."

"The value of this property is a path relative to `src/main/resources/META-INF/resources/`, ..."

2024-07-16 09:22 UTC, knstvk commented on content/modules/flow-ui/pages/themes/pluggable-styles.adoc
> += Pluggable Styles
I think it should be added to the root "Themes" section after "Reusable Theme". It's short and talks about related topic.

2024-07-16 09:22 UTC, knstvk commented on content/modules/flow-ui/pages/themes/styling-ui-components.adoc
> += Styling UI Components
I think we should place this section inside "Visual Components", as a last item. And make cross-references with "Themes".

2024-07-21 11:00 UTC, glebfox commented on content/modules/flow-ui/pages/themes/styling-ui-components.adoc
> += Styling UI Components
I'd rather keep this section here. While it seems logical to move this section, users are more likely to look for information about styling components in the themes section than in the components section

2024-07-22 09:21 UTC, knstvk requested changes

2024-07-22 09:21 UTC, knstvk commented on content/modules/flow-ui/pages/themes/themes.adoc
> +image::themes/theme-folder-structure.png[align="center", width="570"]
Sorry, but you need to divide the retina image width by 2. So in this case it should be `width="285"`.
Then it is shown naturally.
Fix for all small images plz.

2024-07-22 09:21 UTC, knstvk commented on content/modules/flow-ui/pages/themes/styling-ui-components.adoc
> +In case, you need to apply styles to a specific component instance, you can use the `classNames` attribute, for example:
"If you need to ..."

2024-07-22 09:21 UTC, knstvk commented on content/modules/flow-ui/pages/themes/styling-ui-components.adoc
> +For example, if you want to apply a background color and a border to a xref:vc/components/textField.adoc[TextField], we need to apply styles to the *shadow part* called `input-field`:
Replace "we"

2024-07-22 10:01 UTC, merged